"""

When changed models, update using:
     $ python manage.py db init
     $ python manage.py db migrate
     $ python manage.py db upgrade

"""

from sqlalchemy import Column, Integer, String, Date, Float, Table
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
import textwrap
from datetime import datetime

from sqlalchemy.ext.declarative import declarative_base

import datetime, json

Base = declarative_base()

def pretty_print(mystr):
    lines = ""
    for line in textwrap.wrap(mystr):
        lines += line + "\n"
    return lines.strip()


class Articles(Base):
    __tablename__ = "articles"
    title1 = Column(String(200), primary_key=True)
    title2 = Column(String(200))
    source1 = Column(String(200))
    source2 = Column(String(200))
    cos_sim = Column(String(200)) 
    happiness = Column(String(200)) 
    harmvirtue = Column(String(200)) 
    harmvice = Column(String(200)) 
    fairnessvirtue = Column(String(200)) 
    fairnessvice = Column(String(200)) 
    ingroupvirtue = Column(String(200)) 
    ingroupvice = Column(String(200)) 
    authorityvirtue = Column(String(200)) 
    authorityvice = Column(String(200)) 
    purityvirtue = Column(String(200)) 
    purityvice = Column(String(200)) 
    moralitygeneral = Column(String(200)) 
    bias_count = Column(String(200)) 
    assertives_count = Column(String(200)) 
    factives_count = Column(String(200)) 
    hedges_count = Column(String(200)) 
    implicatives_count = Column(String(200)) 
    report_verbs_count = Column(String(200)) 
    positive_op_count = Column(String(200)) 
    negative_op_count = Column(String(200)) 
    wneg_count = Column(String(200)) 
    wpos_count = Column(String(200)) 
    wneu_count = Column(String(200)) 
    sneg_count = Column(String(200)) 
    spos_count = Column(String(200)) 
    sneu_count = Column(String(200)) 
    ttr = Column(String(200)) 
    vad_neg = Column(String(200)) 
    vad_neu = Column(String(200)) 
    vad_pos = Column(String(200)) 
    fke = Column(String(200)) 
    smog = Column(String(200)) 
    stop = Column(String(200)) 
    wordlen = Column(String(200)) 
    wc = Column(String(200)) 
    nb_pobj = Column(String(200)) 
    nb_psubj = Column(String(200)) 
    quotes = Column(String(200)) 
    exclaim = Column(String(200)) 
    allpunc = Column(String(200)) 
    allcaps = Column(String(200)) 
    cc = Column(String(200)) 
    cd = Column(String(200)) 
    dt = Column(String(200)) 
    ex = Column(String(200)) 
    fw = Column(String(200)) 
    in1 = Column(String(200)) 
    jj = Column(String(200)) 
    jjr = Column(String(200)) 
    jjs = Column(String(200)) 
    ls = Column(String(200)) 
    md = Column(String(200)) 
    nn = Column(String(200)) 
    nns = Column(String(200)) 
    nnp = Column(String(200)) 
    nnps = Column(String(200)) 
    pdt = Column(String(200)) 
    pos = Column(String(200)) 
    prp = Column(String(200)) 
    prp1 = Column(String(200)) 
    rb = Column(String(200)) 
    rbr = Column(String(200)) 
    rbs = Column(String(200)) 
    rp = Column(String(200)) 
    sym = Column(String(200)) 
    to1 = Column(String(200)) 
    uh = Column(String(200)) 
    wp1 = Column(String(200)) 
    wrb = Column(String(200)) 
    vb = Column(String(200)) 
    vbd = Column(String(200)) 
    vbg = Column(String(200)) 
    vbn = Column(String(200)) 
    vbp = Column(String(200)) 
    vbz = Column(String(200)) 
    wdt = Column(String(200)) 
    wp = Column(String(200)) 
    ingest = Column(String(200)) 
    cause = Column(String(200)) 
    insight = Column(String(200)) 
    cogmech = Column(String(200)) 
    sad = Column(String(200)) 
    inhib = Column(String(200)) 
    certain = Column(String(200)) 
    tentat = Column(String(200)) 
    discrep = Column(String(200)) 
    space = Column(String(200)) 
    time = Column(String(200)) 
    excl = Column(String(200)) 
    incl = Column(String(200)) 
    relativ = Column(String(200)) 
    motion = Column(String(200)) 
    quant = Column(String(200)) 
    number = Column(String(200)) 
    swear = Column(String(200)) 
    funct = Column(String(200)) 
    ppron = Column(String(200)) 
    pronoun = Column(String(200)) 
    we = Column(String(200))
    i = Column(String(200)) 
    shehe = Column(String(200)) 
    you = Column(String(200)) 
    ipron = Column(String(200)) 
    they = Column(String(200)) 
    death = Column(String(200)) 
    bio = Column(String(200)) 
    body = Column(String(200)) 
    hear = Column(String(200)) 
    feel = Column(String(200)) 
    percept = Column(String(200)) 
    see = Column(String(200)) 
    filler = Column(String(200)) 
    health = Column(String(200)) 
    sexual = Column(String(200)) 
    social = Column(String(200)) 
    family = Column(String(200)) 
    friend = Column(String(200)) 
    humans = Column(String(200)) 
    affect = Column(String(200)) 
    posemo = Column(String(200)) 
    negemo = Column(String(200)) 
    anx = Column(String(200)) 
    anger = Column(String(200)) 
    assent = Column(String(200)) 
    nonfl = Column(String(200)) 
    verb = Column(String(200)) 
    article = Column(String(200)) 
    past = Column(String(200)) 
    auxverb = Column(String(200)) 
    future = Column(String(200)) 
    present = Column(String(200)) 
    preps = Column(String(200)) 
    adverb = Column(String(200)) 
    negate = Column(String(200)) 
    conj = Column(String(200)) 
    home = Column(String(200)) 
    leisure = Column(String(200)) 
    achieve = Column(String(200)) 
    work = Column(String(200)) 
    relig = Column(String(200)) 
    money = Column(String(200)) 
    normal_display = Column(String(2000)) 
    lower_display = Column(String(2000)) 
    sources_display = Column(String(2000))
    title1_date = Column(Date)
    title2_date = Column(Date)
